title: Elyse Y. Robinson | Black American Woman in México
url: "https://elyserobinson.com"
baseurl: "/"
description: Story of one Black American woman's adventures in México...
keywords: ["change architect", "black american expat", "black american immigrant", "black american in mexico", "black american podcast", "beaforeigner", "black and overseas", "black blogger"]
timezone:          Americas/Mexico_City
excerpt_separator: <!--more-->
permalink:         /:title

owner:
  name: elyse y. robinson
  avatar: me.jpg
  job: "Story of one Black American woman's adventures in México 🌮"
  bio: "Change Architect 💰 BeAForeigner Inc."
  email:
  disqus-shortname:
  twitter: mselyserobinson
  amazon-author: amazon.com/hz/wishlist/ls/1TGA5YKKAJ16E
  facebook: mselyserobinson
  paypal: https://paypal.me/sugarcollins
  google:
    plus: #username
    analytics: UA-79873299-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github:
  gitlab: #username
  stackoverflow:
  linkedin:
  skype:
  xing: #username
  instagram: mselyserobinson
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble:
  youtube: elyserobinson
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen:
  reddit: #username
  telegram: #username
  tripadvisor :
  strava:

markdown: kramdown
ins_logo: "/img/me.jpg"

tracking_id: UA-79873299-2

footer: yes
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "home"
   link: "/"
 - name: "about elyse"
   link: "/about"
 - name: "beaforeigner"
   link: "/beaforeigner"
 - name: "insurance"
   link: "/insurance"
 - name: "podcast-youtube"
   link: "/podcast-youtube"
 - name: "travel-deals"
   link: "/travel-deals"
 - name: "search"
   link: "/search"
 - name: "archives"
   link: "/archives"
 - name: "contact"
   link: "/contact"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 7
paginate_path: "/pages/page:num/"
