title: Elyse Y. Robinson | Black American Woman in México
url: "https://elyserobinson.com"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-79873299-2

footer: yes
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "about"
   link: "/about"
 - name: "archives"
   link: "/archives"
 - name: "contact"
   link: "/contact"
 - name: "beaforeigner"
   link: "/beaforeigner"
 - name: "contact"
   link: "/contact"
 - name: "insurance"
   link: "insurance"
 - name: "podcast-youtube"
   link: "/podcast-youtube"
 - name: "search"
   link: "/search"
 - name: "travel-deals"
   link: "/travel-deals"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 7
paginate_path: "/pages/page:num/"
