title: Elyse Y. Robinson | Black American Woman in México
url: "https://elyserobinson.com"
baseurl: "/"
description: Story of one Black American woman's adventures in México...
timezone: Americas/Mexico_City

markdown: kramdown
ins_logo: "/img/me.jpg"

tracking_id: UA-79873299-2

footer: yes
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "home"
   link: "/"
 - name: "about elyse"
   link: "/about"
 - name: "beaforeigner"
   link: "/beaforeigner"
 - name: "insurance"
   link: "/insurance"
 - name: "podcast-youtube"
   link: "/podcast-youtube"
 - name: "travel-deals"
   link: "/travel-deals"
 - name: "search"
   link: "/search"
 - name: "archives"
   link: "/archives"
 - name: "contact"
   link: "/contact"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 7
paginate_path: "/pages/page:num/"
